### ISSUE TITLE
Hand clipping through blocks

### ISSUE THREAD

**Issue by An0therOne** [Ladysnake/Effective#274]
![Screenshot_111](https://github.com/user-attachments/assets/77225c2f-9b4c-4af9-a4b4-e779209c24d1)
![Screenshot_112](https://github.com/user-attachments/assets/014ea01f-a58c-4b34-8597-afb62fbb9b22)
I'm making a modpack and edding effective causes this to happen, the player's hand clips through blocks, the only solution I found was to all around not have effective in the modpack, I'm leaving it here since I haven't seen somebody else have this issue.

Or maybe it's just an issue of compatibility, who knows, I'll leave the log here.

https://mclo.gs/vZM0Fq9

**Comment by viscountexx** [comment]
Came here because I was having the same issue with my own modpack. Just tested on a completely fresh 1.20.1 instance running Quilt 0.26.4 (same versions as my modpack) and the issue doesn't happen, so it must be an incompatibility. I'll try adding a couple mods and see if I can narrow it down.

**Comment by viscountexx** [comment]
Found it! It's Iris. The issue happens with V1.7.2+mc1.20.1 andV1.7.1+mc1.20.1, I tried testing older Iris versions, but frankly I got tired of trying to sus out random dependency mismatches and crashes. I'd assume this either happens in all Iris versions, or specifically 1.7.0 or something. 
Iris does have Sodium as a dependency, but the error only occurs when Iris is installed.

In my testing, the issue affects Effective 2.2.2+1.20.1 thru 2.3.2+1.20.1, and not any earlier.

**Comment by vesmaybevesper** [comment]
A bit more information I have collected in the hope its helpful. It's still occurring on with the new Iris update (1.7.5). While it occurs in the Overworld and Nether I don't seem to have the issue in the End.

I have one mod list where the issue isn't present despite being on 2.3.2 (Iris 1.7.5), I'm still trying to figure out why that is.

**Comment by Xiribidus** [comment]
> I have one mod list where the issue isn't present despite being on 2.3.2 (Iris 1.7.5), I'm still trying to figure out why that is.

Any luck figuring it out? If not I could try testing a bit later today if you give me a list of mods + versions and loader version

**Comment by HorkLord** [comment]
I downgraded my Iris from 1.7.5 for 1.20.1 to 1.7.2 and that has solved the issue. 1.7.5 seems to bug out with the current version of effective and this is the only solution I have found so far.

**Comment by vesmaybevesper** [comment]
> Any luck figuring it out? If not I could try testing a bit later today if you give me a list of mods + versions and loader version

Never got a noti for this sorry. I got distracted by other projects and never got around to testing it (though I have confirmed its not resource or shaderpack related nor does it seem to be 3D Skin Layers). Here's the mod list if you're still willing to look into it:
1.20.1 Quilt 0.26.4
![image](https://github.com/user-attachments/assets/c6a22f22-de21-4101-8b1f-3ad2f4c6d782)
![image](https://github.com/user-attachments/assets/e4e34be6-51bd-4497-9456-c8fbc2382dd7)

Let me know if you need any more info from me for your testing, I've made sure notifications for this are on now.

**Comment by magistr-of-code** [comment]
Blanket fixed it for me.

**Comment by drippyV2** [comment]
still happening for me even with Blanket

**Comment by doctor4t** [comment]
Does it still happen in the latest alphas?

**Comment by steventylerseanherr** [comment]
just tried with iris 1.8.8 for fabric 1.21.1 and effective 2.4.8-1.21.1
it does not happen
so its fixed there atleast
can i ask if the fix would be backported to 1.20.1?

**Comment by nellePoint** [comment]
it does seem fixed in modern versions for me as well, but am also having the issue on 1.20.1

**Comment by Josh-Des** [comment]
Everyone!

I found a way for it to work with Iris, I used a shaderpack called Sildurs Vibrant Shaders Lite and it worked it's not clipping no more, I'm not sure if it works with other shaders but the shader I gave works.

**Comment by amzelee** [comment]
Still occurs  in 1.20.1 with the latest version of both iris and effective

**Comment by XXMarionetteXX** [comment]
Fixed! Sorta... 
It's something in the iris properties file in the config folder. 
Did some testing with two modpacks, one I made prior to the issue a few months back and a recent one, and what makes the difference is that properties file. Without it, hand glitch, with the right version from the old modpack, hand doesn't phase at all.

**Comment by XXMarionetteXX** [comment]
No clue as of right now what particular property it is though...

**Comment by XXMarionetteXX** [comment]
Versions I used were effective 2.3.2, iris 1.7.5, and sodium 0.5.11. This is on fabric 1.20.1 0.16.10
